# Generated by Django 3.0.3 on 2020-02-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0002_auto_20200217_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devis.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='LineFacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('qte', models.IntegerField()),
                ('puht', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linefacture', to='facture.Facture')),
            ],
        ),
    ]
