# Generated by Django 3.0.3 on 2020-02-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturier', '0004_auto_20200213_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LineDevis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('qte', models.IntegerField()),
                ('puht', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devis.Devis')),
            ],
        ),
    ]
