# Generated by Django 3.0.3 on 2020-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=10)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('siret', models.IntegerField(max_length=14)),
                ('tva', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
