# Generated by Django 3.0.3 on 2020-02-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100, null=True)),
                ('zipcode', models.IntegerField(max_length=5, null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Client')),
            ],
        ),
    ]
