# Generated by Django 3.0.3 on 2020-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressType',
            field=models.CharField(blank=True, choices=[('SH', 'Livraison'), ('BL', 'Facturation'), ('HQ', 'Siège Social')], max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
