# Generated by Django 3.0.3 on 2020-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0003_auto_20200213_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
